# This file was generated by GoReleaser. DO NOT EDIT.
class Usacloud < Formula
  desc ""
  homepage "https://github.com/sacloud/usacloud"
  version "0.0.99"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.99/usacloud_darwin-amd64.zip"
    sha256 "99b4cee8e9464537eabcd06e71e0e7b34544c4d7e62913e753698b974dfc1993"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.99/usacloud_linux-amd64.zip"
    sha256 "a10954de75343f73429d637dd5ff686506d73a2f89e4ec87359d81ac6203b4ee"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.99/usacloud_linux-arm.zip"
    sha256 "169e09d88d02e1a27853d9015428315869abb12b15ec085864124ddcab082e7a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.99/usacloud_linux-arm64.zip"
    sha256 "8a243b8ac309f9025d3fdde9f9c438bcb7ef3b6859c6ecf9d5c30cacb2b9f23a"
  end

  def install
    bin.install "usacloud"
  end

  test do
    system "#{bin}/usacloud --version"
  end
end
