# This file was generated by GoReleaser. DO NOT EDIT.
class Usacloud < Formula
  desc ""
  homepage "https://github.com/sacloud/usacloud"
  version "0.0.100"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.100/usacloud_darwin-amd64.zip"
    sha256 "44488ee3d3af61782f31cf244fe2d56fffdeb041dda63b50dafb30d83ac61ace"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.100/usacloud_linux-amd64.zip"
    sha256 "3daf505689bc07480a957252bcadedb742ca0977660a7791c29b3a76d6ef732f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.100/usacloud_linux-arm.zip"
    sha256 "66aa8876c14f8938595a9da63d8749e73f6d0c96032c624b1e0f2a886fae1ff8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/yamamoto-febc/usacloud/releases/download/v0.0.100/usacloud_linux-arm64.zip"
    sha256 "f4857fbc118ace0d5394ff1885745edf387af4126728b47f25e4b4aa027f84d5"
  end

  def install
    bin.install "usacloud"
  end

  test do
    system "#{bin}/usacloud --version"
  end
end
